### ISSUE TITLE
Firebase.framework-2.3.3.zip  create-dirs

### ISSUE THREAD

**Issue by oucart** [amitburst/HackerNews#26] opened 2015-11-20 12:59 UTC
pengtingdeMacBook-Pro:HackerNews patrick$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Firebase (2.3.3)

[!] Error installing Firebase
[!] /usr/bin/curl -f -L -o /var/folders/fz/k44v3dq925nb2f6vdklx6rw40000gn/T/d20151120-3687-kwt8qu/file.zip https://cdn.firebase.com/ObjC/Firebase.framework-2.3.3.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 13 8155k   13 1087k    0     0   1687      0  1:22:30  0:10:59  1:11:31     0curl: (18) transfer closed with 7237202 bytes remaining to read

**Comment by amitburst** [comment] 2015-11-22 00:13
Hmm, `pod install` works just fine for me. Are you using an updated version of CocoaPods?

**Comment by oucart** [comment] 2015-11-22 01:33
pengtingdeMacBook-Pro:HackerNews patrick$ pod --version
0.39.0

**Comment by amitburst** [comment] 2015-11-22 19:20
Save version as me... I pushed a new change yesterday which updates the Firebase dependency version, so try pulling in that change and see if `pod install` works after that.

**Comment by oucart** [comment] 2015-11-23 07:15
same

[!] /usr/bin/curl -f -L -o /var/folders/fz/k44v3dq925nb2f6vdklx6rw40000gn/T/d20151123-1187-14fvdyl/file.zip https://cdn.firebase.com/ObjC/Firebase.framework-2.4.3.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to cdn.firebase.com port 443: Connection reset by pee

**Comment by amitburst** [comment] 2015-11-23 07:32
That's a different error code (7). It looks like you can't connect to cdn.firebase.com. What happens if you try to download https://cdn.firebase.com/ObjC/Firebase.framework-2.4.3.zip directly?

**Comment by oucart** [comment] 2015-11-23 07:51
I can download

**Comment by amitburst** [comment] 2015-11-24 02:05
Then this sounds like an issue with your `curl` or `pod` install. Try re-installing CocoaPods and curl (unless you're using the version that came with your OS), and if that doesn't work, I would file a bug against CocoaPods. Haven't seen this issue come up before myself and I haven't received any similar bug reports.

**Comment by amitburst** [comment] 2015-12-01 04:49
I'm gonna close this out for now, but feel free to re-open if you find that the issue is in this project.

**Closed by amitburst** 2015-12-01 04:49 UTC

**Comment by swinghu** [comment] 2016-02-10 13:12
Hi, I meet the problem 
when run
pod install --verbose --no-repo-update
pod file 
`latform :ios, '8.0'
use_frameworks!

target 'FirebaseJokes' do
    pod 'Firebase', '>= 2.5.0'
end

target 'FirebaseJokesTests' do
    pod 'Firebase', '>= 2.5.0'
end

target 'FirebaseJokesUITests' do
    pod 'Firebase', '>= 2.5.0'
end`

The error msg
`-> Installing Firebase (2.5.0)
 > Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/gg/3xhhqth56rzctt883bbmys300000gn/T/d20160210-1147-1uyxzzn/file.zip
   https://cdn.firebase.com/ObjC/Firebase.framework-2.5.0.zip --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) Unknown SSL protocol error in connection to cdn.firebase.com:-36

[!] Error installing Firebase
[!] /usr/bin/curl -f -L -o /var/folders/gg/3xhhqth56rzctt883bbmys300000gn/T/d20160210-1147-1uyxzzn/file.zip https://cdn.firebase.com/ObjC/Firebase.framework-2.5.0.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) Unknown SSL protocol error in connection to cdn.firebase.com:-36
`
pod version : 
ios-dev/FirebaseJokesStarter$ pod --version
1.0.0.beta.3

**Comment by amitburst** [comment] 2016-02-11 06:43
I think you filed this in the wrong project.
